import { createClientFromRequest } from 'npm:@base44/sdk@0.8.52';
import { secrets } from 'base44:runtime';

export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const body = await req.json().catch(() => ({}));
    const expectedSecret = secrets.get('WORKER_SECRET');
    const isWorker = !!(body?.worker_secret && expectedSecret && body.worker_secret === expectedSecret);
    if (!isWorker) { const user = await base44.auth.me(); if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 }); }

    const repoName = (body.repo_name || '').trim();
    if (!repoName) return Response.json({ error: 'repo_name required' }, { status: 400 });

    let accessToken;
    try { const conn = await base44.asServiceRole.connectors.getConnection('github'); accessToken = conn.accessToken; } catch (e) {
      return Response.json({ needs_auth: true, message: 'GitHub connector not authorized. Authorize it from the Integration Stack, then retry.' });
    }

    const res = await fetch('https://api.github.com/user/repos', { method: 'POST', headers: { Authorization: `Bearer ${accessToken}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json' }, body: JSON.stringify({ name: repoName, description: body.description || 'Auto-generated by Website Factory', private: false, auto_init: true }) });
    if (!res.ok) { const errText = await res.text().catch(() => ''); return Response.json({ error: `GitHub API error: ${res.status} ${errText.slice(0, 200)}` }, { status: 502 }); }

    const repo = await res.json();
    return Response.json({ repo_url: repo.html_url, repo_name: repo.full_name, clone_url: repo.clone_url });
  } catch (error) { return Response.json({ error: error.message }, { status: 500 }); }
}