import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Loader2, Rocket, ExternalLink, CheckCircle2, AlertCircle, Globe, Code2 } from "lucide-react";

export default function WebsiteBuilder() {
  const [niche, setNiche] = useState("");
  const [style, setStyle] = useState("");
  const [businessName, setBusinessName] = useState("");
  const [building, setBuilding] = useState(false);
  const [stage, setStage] = useState("");
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  const build = async () => {
    if (!niche.trim()) return;
    setBuilding(true); setError(null); setResult(null); setStage("Generating website code via AI Gateway…");
    try {
      const res = await base44.functions.invoke("runWebsiteBuilder", {
        niche: niche.trim(), style: style.trim() || "modern professional", business_name: businessName.trim(),
      });
      const data = res.data || res;
      if (data.error && !data.deploy_url) { setError(data.error); } else { setResult(data); if (data.error) setError(data.error); }
    } catch (e) { setError(e.response?.data?.error || e.message || "Build failed."); }
    setBuilding(false); setStage("");
  };

  return (
    <section className="xa-card p-5">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-9 h-9 rounded-lg bg-muted flex items-center justify-center"><Globe className="w-5 h-5 text-muted-foreground" /></div>
        <div>
          <h2 className="font-heading font-bold text-lg text-black">Build & Deploy a Real Website</h2>
          <p className="text-xs text-black/50">AI generates a complete website and deploys it to a live Vercel URL — not a spec, not a plan, a real site.</p>
        </div>
      </div>

      <div className="space-y-3">
        <input className="xa-input" placeholder="Business name (optional): Bright Smile Dental" value={businessName} onChange={e => setBusinessName(e.target.value)} disabled={building} />
        <input className="xa-input" placeholder="Niche: dental practice, plumbing, landscaping…" value={niche} onChange={e => setNiche(e.target.value)} disabled={building} />
        <input className="xa-input" placeholder="Style: modern, warm, professional, minimal…" value={style} onChange={e => setStyle(e.target.value)} disabled={building} />

        <button onClick={build} disabled={building || !niche.trim()} className="xa-btn-primary w-full py-3">
          {building ? <><Loader2 className="w-4 h-4 animate-spin" /> {stage}</> : <><Rocket className="w-4 h-4" /> Build & Deploy Website</>}
        </button>

        {error && (
          <div className="flex items-start gap-2 p-3 rounded-lg bg-red-50 border border-red-200 text-xs text-red-700">
            <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" /><span>{error}</span>
          </div>
        )}

        {result && result.deploy_url && (
          <div className="space-y-3">
            <div className="flex items-center gap-2 p-3 rounded-lg bg-green-50 border border-green-200">
              <CheckCircle2 className="w-5 h-5 text-green-600 shrink-0" />
              <div className="min-w-0 flex-1">
                <div className="text-sm font-bold text-green-700">Website deployed!</div>
                <a href={result.deploy_url} target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 hover:underline truncate block">{result.deploy_url}</a>
              </div>
              <a href={result.deploy_url} target="_blank" rel="noopener noreferrer" className="xa-btn-primary text-xs px-3 py-2 shrink-0"><ExternalLink className="w-3.5 h-3.5" /> Visit</a>
            </div>
            <div className="rounded-xl overflow-hidden border border-[#E5E7EB] bg-white">
              <div className="flex items-center gap-2 px-3 py-2 border-b border-[#E5E7EB] bg-[#FAFAFA]">
                <Code2 className="w-3.5 h-3.5 text-black/40" />
                <span className="text-xs font-bold text-black/60">Live Preview</span>
                <span className="text-xs text-black/30 truncate ml-auto">{result.deploy_url?.replace('https://', '')}</span>
              </div>
              <iframe src={result.deploy_url} title="Website preview" className="w-full" style={{ height: "400px", border: 0 }} />
            </div>
            <div className="text-xs text-black/40 px-1">Generated by {result.ai_model} · Deployed to Vercel · {result.html?.length || 0} chars of HTML</div>
          </div>
        )}
      </div>
    </section>
  );
}