const plugin = require('tailwindcss/plugin');

// Normalize every pre-rebrand utility at build time. Hover, responsive and dark
// variants are generated by Tailwind too, so legacy pages share the same tokens.
const carbonLegacy = plugin(({ addUtilities, e }) => {
  const utilities = {};
  const shades = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
  const opacities = [null, 5, 10, 15, 20, 25, 30, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100];
  const emit = (name, token, opacity, type) => {
    const color = `hsl(var(--${token}) / ${opacity == null ? 1 : opacity / 100})`;
    let rule;
    if (type === 'from') rule = { '--tw-gradient-from': `${color} var(--tw-gradient-from-position)`, '--tw-gradient-to': `hsl(var(--${token}) / 0) var(--tw-gradient-to-position)`, '--tw-gradient-stops': 'var(--tw-gradient-from), var(--tw-gradient-to)' };
    else if (type === 'via') rule = { '--tw-gradient-to': `hsl(var(--${token}) / 0) var(--tw-gradient-to-position)`, '--tw-gradient-stops': `var(--tw-gradient-from), ${color} var(--tw-gradient-via-position), var(--tw-gradient-to)` };
    else if (type === 'to') rule = { '--tw-gradient-to': `${color} var(--tw-gradient-to-position)` };
    else rule = { [{ bg: 'backgroundColor', text: 'color', border: 'borderColor', ring: '--tw-ring-color', accent: 'accentColor', fill: 'fill', stroke: 'stroke' }[type]]: color };
    if (type === 'bg') rule['--legacy-action-text'] = ['primary', 'success', 'info', 'destructive', 'warning'].includes(token) && (opacity == null || opacity >= 80) ? 'hsl(var(--primary-foreground))' : 'initial';
    utilities[`.${e(`${type}-${name}${opacity == null ? '' : `/${opacity}`}`)}`] = rule;
  };
  const types = ['bg', 'text', 'border', 'ring', 'from', 'via', 'to', 'accent', 'fill', 'stroke'];
  for (const family of ['slate', 'gray', 'zinc', 'neutral', 'stone']) {
    for (const shade of shades) for (const opacity of opacities) for (const type of types) {
      const token = type === 'text' ? (shade >= 700 || shade <= 200 ? 'foreground' : 'muted-foreground') : type === 'border' || type === 'ring' ? 'border' : shade >= 800 ? 'background' : shade <= 100 ? 'card' : 'muted';
      emit(`${family}-${shade}`, token, opacity, type);
    }
  }
  for (const family of ['amber', 'yellow', 'orange', 'purple', 'violet', 'indigo']) {
    for (const shade of shades) for (const opacity of opacities) for (const type of types) {
      const effectiveOpacity = type === 'bg' && shade <= 200 && opacity == null ? 12 : opacity;
      emit(`${family}-${shade}`, 'primary', effectiveOpacity, type);
    }
  }
  for (const family of ['red', 'rose', 'pink', 'green', 'emerald', 'teal', 'blue', 'sky', 'cyan']) {
    const token = ['red', 'rose', 'pink'].includes(family) ? 'destructive' : ['green', 'emerald', 'teal'].includes(family) ? 'success' : 'info';
    for (const shade of shades) for (const opacity of opacities) for (const type of types) {
      emit(`${family}-${shade}`, token, type === 'bg' && shade <= 200 && opacity == null ? 12 : opacity, type);
    }
  }
  for (const opacity of opacities) {
    emit('white', 'card', opacity, 'bg');
    emit('white', 'card', opacity, 'from'); emit('white', 'card', opacity, 'to');
    emit('black', opacity == null || opacity >= 80 ? 'foreground' : 'muted-foreground', opacity, 'text');
    // Keep dark text only on a filled brand action, never on carbon panels.
    const selector = `.${e(`text-black${opacity == null ? '' : `/${opacity}`}`)}`;
    utilities[selector].color = `var(--legacy-action-text, hsl(var(--${opacity == null || opacity >= 80 ? 'foreground' : 'muted-foreground'})))`;
  }
  const hexTokens = {
    '#FAFAFA': 'background', '#FFF': 'card', '#FFFFFF': 'card', '#fff': 'card', '#ffffff': 'card',
    '#E5E7EB': 'border', '#e5e7eb': 'border', '#FFF7B3': 'primary', '#FFEA00': 'primary', '#E6D400': 'primary', '#CCBB00': 'primary', '#8A7300': 'primary',
    '#121214': 'background', '#161619': 'sidebar-background', '#171719': 'background', '#191a1c': 'card', '#18191b': 'card',
    '#34363a': 'border', '#34373a': 'border', '#36383b': 'border', '#414347': 'border', '#45484b': 'border', '#53565b': 'border', '#424448': 'border', '#2a2c2f': 'border', '#2c2d30': 'border', '#333': 'border', '#48494b': 'border',
    '#ff8800': 'primary', '#ffa333': 'warning', '#ffae52': 'warning', '#b95700': 'primary', '#c96708': 'primary', '#754313': 'border', '#51402e': 'border', '#1d1a16': 'card',
    '#e7e8e9': 'foreground', '#c0c1c3': 'foreground', '#b5b8bc': 'muted-foreground', '#aeb1b4': 'muted-foreground', '#9ca3af': 'muted-foreground', '#777d83': 'muted-foreground', '#85898d': 'muted-foreground', '#999': 'muted-foreground',
    '#171514': 'primary-foreground', '#151413': 'primary-foreground'
  };
  for (const [hex, token] of Object.entries(hexTokens)) for (const opacity of opacities) for (const type of types) {
    emit(`[${hex}]`, token, type === 'bg' && hex === '#FFF7B3' && opacity == null ? 12 : opacity, type);
  }
  addUtilities(utilities);
  addUtilities({
    '.bg-primary, .bg-gold-gradient, .xa-btn-primary': { '--legacy-action-text': 'hsl(var(--primary-foreground))' },
    '.text-primary-foreground': { color: 'hsl(var(--primary-foreground))' },
    '.text-white': { color: 'var(--legacy-action-text, hsl(var(--foreground)))' },
    '.rounded-xl, .rounded-2xl, .rounded-3xl': { borderRadius: 'var(--radius)' },
  });
});

/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
  	extend: {
  		borderRadius: {
  			lg: 'var(--radius)',
  			md: 'calc(var(--radius) - 2px)',
  			sm: 'calc(var(--radius) - 4px)'
  		},
  		colors: {
  			background: 'hsl(var(--background))',
  			foreground: 'hsl(var(--foreground))',
  			card: {
  				DEFAULT: 'hsl(var(--card))',
  				foreground: 'hsl(var(--card-foreground))'
  			},
  			popover: {
  				DEFAULT: 'hsl(var(--popover))',
  				foreground: 'hsl(var(--popover-foreground))'
  			},
  			primary: {
  				DEFAULT: 'hsl(var(--primary))',
  				foreground: 'hsl(var(--primary-foreground))'
  			},
  			secondary: {
  				DEFAULT: 'hsl(var(--secondary))',
  				foreground: 'hsl(var(--secondary-foreground))'
  			},
  			muted: {
  				DEFAULT: 'hsl(var(--muted))',
  				foreground: 'hsl(var(--muted-foreground))'
  			},
  			accent: {
  				DEFAULT: 'hsl(var(--accent))',
  				foreground: 'hsl(var(--accent-foreground))'
  			},
  			destructive: {
  				DEFAULT: 'hsl(var(--destructive))',
  				foreground: 'hsl(var(--destructive-foreground))'
  			},
  			success: 'hsl(var(--success) / <alpha-value>)',
			info: 'hsl(var(--info) / <alpha-value>)',
			warning: 'hsl(var(--warning) / <alpha-value>)',
			border: 'hsl(var(--border))',
  			input: 'hsl(var(--input))',
  			ring: 'hsl(var(--ring))',
  			chart: {
  				'1': 'hsl(var(--chart-1))',
  				'2': 'hsl(var(--chart-2))',
  				'3': 'hsl(var(--chart-3))',
  				'4': 'hsl(var(--chart-4))',
  				'5': 'hsl(var(--chart-5))'
  			},
  			sidebar: {
  				DEFAULT: 'hsl(var(--sidebar-background))',
  				foreground: 'hsl(var(--sidebar-foreground))',
  				primary: 'hsl(var(--sidebar-primary))',
  				'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
  				accent: 'hsl(var(--sidebar-accent))',
  				'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
  				border: 'hsl(var(--sidebar-border))',
  				ring: 'hsl(var(--sidebar-ring))'
  			}
  		},
  		fontFamily: {
  			heading: ['var(--font-heading)'],
  			body: ['var(--font-body)'],
  			display: ['var(--font-display)'],
  			mono: ['var(--font-mono)']
  		},
  		keyframes: {
  			'accordion-down': {
  				from: {
  					height: '0'
  				},
  				to: {
  					height: 'var(--radix-accordion-content-height)'
  				}
  			},
  			'accordion-up': {
  				from: {
  					height: 'var(--radix-accordion-content-height)'
  				},
  				to: {
  					height: '0'
  				}
  			}
  		},
  		animation: {
  			'accordion-down': 'accordion-down 0.2s ease-out',
  			'accordion-up': 'accordion-up 0.2s ease-out'
  		}
  	}
  },
  plugins: [require("tailwindcss-animate"), carbonLegacy],
}
