// Comprehensive capability registry — current system + 3 imported projects + all possible capabilities + gaps
// Sources: Cloud Browser (current), Xtreme AI Builder, Fault-Line 3, Vision Cortex

export const SYSTEM_SOURCES = [
  { id: 'cloud_browser', name: 'Cloud Browser (Current)', color: 'blue', icon: 'Cloud' },
  { id: 'xtremeaibuilder', name: 'Xtreme AI Builder', color: 'purple', icon: 'Sparkles' },
  { id: 'faultline', name: 'Fault-Line 3', color: 'orange', icon: 'AlertTriangle' },
  { id: 'visioncortex', name: 'Vision Cortex', color: 'green', icon: 'Eye' },
];

// === ALL CURRENT SYSTEM CAPABILITIES ===
export const CURRENT_CAPABILITIES = [
  // Infrastructure
  { category: 'Infrastructure', name: 'Headless Chrome Fleet', status: 'implemented', score: 95, source: 'cloud_browser', description: 'Railway-hosted Playwright/CDP browser engine with persistent profiles' },
  { category: 'Infrastructure', name: 'Session Pooling', status: 'implemented', score: 90, source: 'cloud_browser', description: 'Pre-warmed session pool with configurable size and warm count' },
  { category: 'Infrastructure', name: 'Auto-Scaling', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Queue-depth and CPU-based autoscaling with min/max pool bounds' },
  { category: 'Infrastructure', name: 'Multi-Region Deployment', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Single-region (EU-West/ams) with persistent volume at /app/profiles' },
  { category: 'Infrastructure', name: 'CDP Debug Protocol', status: 'implemented', score: 90, source: 'cloud_browser', description: 'Chrome DevTools Protocol endpoint for live debugging' },
  { category: 'Infrastructure', name: 'Video Recording', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Session video recording with configurable retention' },
  { category: 'Infrastructure', name: 'Persistent Profiles', status: 'implemented', score: 88, source: 'cloud_browser', description: 'Encrypted cookie/storage state persistence across sessions' },
  { category: 'Infrastructure', name: 'Multi-Tab Management', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Tab creation, switching, closing with state tracking' },
  { category: 'Infrastructure', name: 'HAR Generator', status: 'implemented', score: 85, source: 'cloud_browser', description: 'HTTP Archive generation for network analysis' },
  { category: 'Infrastructure', name: 'Session Resume', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Resume tokens for continuing interrupted sessions' },
  { category: 'Infrastructure', name: 'Live View Sharing', status: 'implemented', score: 78, source: 'cloud_browser', description: 'Share-token based live session viewing' },
  { category: 'Infrastructure', name: 'Browser Context Leasing', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Context lock/lease with expiry for concurrent access control' },

  // Anti-Detection
  { category: 'Anti-Detection', name: 'rebrowser-playwright', status: 'implemented', score: 90, source: 'cloud_browser', description: 'CDP automation detection bypass via rebrowser-playwright' },
  { category: 'Anti-Detection', name: 'Browser Fingerprint Randomizer', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Randomized platform, plugins, fonts, canvas noise, webdriver' },
  { category: 'Anti-Detection', name: 'TLS/JA3/JA4 Fingerprinting', status: 'implemented', score: 82, source: 'cloud_browser', description: 'TLS fingerprint config with JA3 hash, JA4, cipher suites, ALPN' },
  { category: 'Anti-Detection', name: 'Human Behavior Simulation', status: 'implemented', score: 88, source: 'cloud_browser', description: 'Bezier curve mouse movement, typing jitter, scroll patterns' },
  { category: 'Anti-Detection', name: 'Anti-Bot Detection Mapping', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Bot detection script identification and bypass strategies' },
  { category: 'Anti-Detection', name: 'Anti-Bot Bypass Strategies', status: 'implemented', score: 83, source: 'cloud_browser', description: 'Comprehensive bypass library for Cloudflare, Datadome, etc.' },
  { category: 'Anti-Detection', name: 'Shadow Mode', status: 'implemented', score: 87, source: 'cloud_browser', description: 'Read-only safe mode that captures site defenses before live execution' },

  // Proxy Management
  { category: 'Proxy Management', name: 'Proxy Rotation', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Round-robin rotation groups with provider API integration' },
  { category: 'Proxy Management', name: 'Geo-Targeting', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Country, city, state, ASN, ZIP-level targeting' },
  { category: 'Proxy Management', name: 'Provider Integration', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Bright Data, Smartproxy, Oxylabs, IPRoyal, Soax support' },
  { category: 'Proxy Management', name: 'Residential/Mobile/Datacenter/ISP', status: 'implemented', score: 85, source: 'cloud_browser', description: 'All IP type support with encrypted credentials' },

  // CAPTCHA
  { category: 'CAPTCHA', name: 'Self-Solving reCAPTCHA v2', status: 'partial', score: 65, source: 'cloud_browser', description: 'Audio transcription-based self-solver (rate-limited on high-security)' },
  { category: 'CAPTCHA', name: 'Self-Solving hCaptcha', status: 'partial', score: 45, source: 'cloud_browser', description: 'Image challenge solver (lacks full image challenge, times out on non-trusted fingerprints)' },
  { category: 'CAPTCHA', name: 'Self-Solving Turnstile', status: 'implemented', score: 75, source: 'cloud_browser', description: 'Cloudflare Turnstile self-solver' },
  { category: 'CAPTCHA', name: '2captcha Fallback', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Automated paid fallback for aggressive reCAPTCHA Enterprise' },
  { category: 'CAPTCHA', name: 'Vision-Based CAPTCHA Solver', status: 'partial', score: 55, source: 'cloud_browser', description: 'LLM vision model for image challenge solving' },

  // AI Core
  { category: 'AI Core', name: 'Self-Healing Selectors', status: 'implemented', score: 88, source: 'cloud_browser', description: 'AI-powered selector repair when DOM changes' },
  { category: 'AI Core', name: 'Intelligent Error-Aware Retries', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Context-aware retry with error pattern classification' },
  { category: 'AI Core', name: 'PII Redaction', status: 'implemented', score: 90, source: 'cloud_browser', description: 'Automatic PII detection and redaction in extracted data' },
  { category: 'AI Core', name: 'Anomaly Detection', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Statistical anomaly detection in extraction results' },
  { category: 'AI Core', name: 'AI Job Builder', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Natural language to automation step conversion' },
  { category: 'AI Core', name: 'AI Chat Agent', status: 'implemented', score: 80, source: 'cloud_browser', description: 'In-app AI assistant with entity access' },
  { category: 'AI Core', name: 'AI Extract', status: 'implemented', score: 85, source: 'cloud_browser', description: 'LLM-powered structured data extraction from pages' },

  // Security
  { category: 'Security', name: 'SSRF Protection', status: 'implemented', score: 92, source: 'cloud_browser', description: 'IP CIDR blocklist, metadata endpoint blocking, DNS rebinding protection' },
  { category: 'Security', name: 'Rate Limiting', status: 'implemented', score: 88, source: 'cloud_browser', description: 'Fixed-window rate limiting with hashed API key tracking' },
  { category: 'Security', name: 'Hashed API Auth', status: 'implemented', score: 90, source: 'cloud_browser', description: 'SHA-256 hashed API keys with scope/project binding' },
  { category: 'Security', name: 'URL Sanitization', status: 'implemented', score: 88, source: 'cloud_browser', description: 'Protocol validation, URL canonicalization, blocklist' },
  { category: 'Security', name: 'Webhook Delivery Signatures', status: 'implemented', score: 85, source: 'cloud_browser', description: 'HMAC-signed webhook payloads with retry tracking' },
  { category: 'Security', name: 'AES-GCM Encryption', status: 'implemented', score: 92, source: 'cloud_browser', description: 'Encrypted proxy passwords, cookies, storage state, credentials' },
  { category: 'Security', name: 'Row-Level Security (RLS)', status: 'implemented', score: 88, source: 'cloud_browser', description: 'Per-entity RLS with admin/user ownership patterns' },
  { category: 'Security', name: 'Audit Logging', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Comprehensive audit trail for all admin operations' },
  { category: 'Security', name: 'IP Allowlist', status: 'implemented', score: 82, source: 'cloud_browser', description: 'IP-based API access restrictions' },
  { category: 'Security', name: 'HTTPS Enforcement', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Optional HTTPS-only navigation policy' },
  { category: 'Security', name: 'Compliance Frameworks', status: 'partial', score: 60, source: 'cloud_browser', description: 'SOC2, HIPAA, GDPR, PCI-DSS, ISO 27001 framework tracking' },

  // Data Extraction
  { category: 'Data Extraction', name: 'Text/HTML/Attribute Extraction', status: 'implemented', score: 90, source: 'cloud_browser', description: 'Extract text, HTML, attributes, tables, JSON from pages' },
  { category: 'Data Extraction', name: 'Screenshot Capture', status: 'implemented', score: 90, source: 'cloud_browser', description: 'Full-page and element screenshot capture' },
  { category: 'Data Extraction', name: 'PDF Generation', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Page-to-PDF conversion' },
  { category: 'Data Extraction', name: 'Crawling & Pagination', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Multi-page crawling with pagination support' },
  { category: 'Data Extraction', name: 'Network Mocking', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Request interception and mock responses' },
  { category: 'Data Extraction', name: 'Response Capture', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Capture API responses during navigation' },
  { category: 'Data Extraction', name: 'Cookie Management', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Set, import, export cookies' },
  { category: 'Data Extraction', name: 'State Save/Restore', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Save and restore browser state across sessions' },

  // Job Management
  { category: 'Job Management', name: 'Job Queue with Priority', status: 'implemented', score: 88, source: 'cloud_browser', description: 'Priority-based job queue with 1-10 priority levels' },
  { category: 'Job Management', name: 'Job Dependencies', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Parent-child job dependencies with completion conditions' },
  { category: 'Job Management', name: 'Fan-Out Jobs', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Run same job across multiple URLs' },
  { category: 'Job Management', name: 'Retry with Backoff', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Configurable max retries with exponential backoff' },
  { category: 'Job Management', name: 'Scheduled Jobs', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Cron-based job scheduling' },
  { category: 'Job Management', name: 'Job Versioning', status: 'implemented', score: 78, source: 'cloud_browser', description: 'Job version tracking with change alerts' },
  { category: 'Job Management', name: 'Kanban Board', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Drag-and-drop job status management' },
  { category: 'Job Management', name: 'Step Builder', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Visual step-by-step automation builder with 40+ action types' },
  { category: 'Job Management', name: 'Templates', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Reusable job templates' },

  // Observability
  { category: 'Observability', name: 'Engine Health Monitoring', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Real-time engine health with uptime tracking' },
  { category: 'Observability', name: 'Error Pattern Grouping', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Fingerprint-based error grouping with affected job tracking' },
  { category: 'Observability', name: 'Cost Tracking', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Tiered cost calculation for compute, proxy, LLM, storage' },
  { category: 'Observability', name: 'Analytics Dashboard', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Traffic, session, and job analytics with charts' },
  { category: 'Observability', name: 'Audit Logs', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Comprehensive admin audit trail' },
  { category: 'Observability', name: 'Change Alerts', status: 'implemented', score: 78, source: 'cloud_browser', description: 'Site change detection and alerting' },
  { category: 'Observability', name: 'Webhook Delivery Tracking', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Webhook delivery logs with retry status' },
  { category: 'Observability', name: 'Notification System', status: 'implemented', score: 80, source: 'cloud_browser', description: 'In-app notifications with polling' },

  // Integrations
  { category: 'Integrations', name: 'GitHub Sync', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Bi-directional GitHub repo sync' },
  { category: 'Integrations', name: 'Railway Deployment', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Railway hosting with persistent volumes' },
  { category: 'Integrations', name: 'Vercel Integration', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Vercel deployment API integration' },
  { category: 'Integrations', name: 'Supabase Integration', status: 'implemented', score: 78, source: 'cloud_browser', description: 'Supabase connector for data persistence' },
  { category: 'Integrations', name: 'Google Workspace', status: 'implemented', score: 75, source: 'cloud_browser', description: 'Drive, Sheets, Docs, Calendar, Tasks, Gmail connectors' },
  { category: 'Integrations', name: 'HubSpot CRM', status: 'implemented', score: 75, source: 'cloud_browser', description: 'HubSpot connector for CRM data' },
  { category: 'Integrations', name: 'Python SDK', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Python SDK for REST API interactions' },
  { category: 'Integrations', name: 'MCP Server', status: 'implemented', score: 78, source: 'cloud_browser', description: 'MCP server for AI client data access' },
  { category: 'Integrations', name: 'Stripe Billing', status: 'partial', score: 60, source: 'cloud_browser', description: 'Stripe integration for subscription billing' },

  // Governance
  { category: 'Governance', name: 'RLS Tenant Isolation', status: 'implemented', score: 88, source: 'cloud_browser', description: 'Row-level security for multi-tenant data isolation' },
  { category: 'Governance', name: 'API Key Scoping', status: 'implemented', score: 85, source: 'cloud_browser', description: 'Project and team-bound API keys with scopes' },
  { category: 'Governance', name: 'Budget Alerts', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Cost budget monitoring with alerts' },
  { category: 'Governance', name: 'Release Gates', status: 'implemented', score: 82, source: 'cloud_browser', description: 'GitHub-based CI/CD quality gates' },
  { category: 'Governance', name: 'Sandbox Isolation', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Isolated, staging, and production sandbox scopes' },
  { category: 'Governance', name: 'Settings Management', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Hierarchical settings with scope inheritance and drift detection' },

  // Testing & QA
  { category: 'Testing & QA', name: 'Capability Test Lab', status: 'implemented', score: 85, source: 'cloud_browser', description: '95 mapped system capabilities with autonomous testing' },
  { category: 'Testing & QA', name: 'Forensic Audit', status: 'implemented', score: 82, source: 'cloud_browser', description: 'Multi-suite forensic audit with proof artifacts' },
  { category: 'Testing & QA', name: 'Nightly Test Automation', status: 'implemented', score: 80, source: 'cloud_browser', description: 'Scheduled workflow for autonomous capability testing' },
  { category: 'Testing & QA', name: 'Staging Test Suite', status: 'implemented', score: 78, source: 'cloud_browser', description: 'Staging environment black-box tests' },
  { category: 'Testing & QA', name: 'Tenant Isolation Tests', status: 'implemented', score: 82, source: 'cloud_browser', description: 'RLS tenant isolation verification tests' },
];

// === CAPABILITIES FROM XTREME AI BUILDER ===
export const XTREMEAI_CAPABILITIES = [
  { category: 'Site Cloning', name: 'Full-Site Clone Engine', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Renders target site via browser engine, extracts HTML/metadata/links/images, discovers pages from sitemap, returns structured clone spec' },
  { category: 'Site Cloning', name: 'Design DNA Extraction', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Extracts colors, fonts, spacing, layout patterns, component structure from scraped HTML/CSS using regex + LLM analysis' },
  { category: 'Site Cloning', name: 'Vision Cortex Compare', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Visual comparison between original site and clone with pixel-level diff analysis' },
  { category: 'Site Cloning', name: 'Vision Cortex Auto-Adjust', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Automatically adjusts clone to match original visual appearance using LLM-driven corrections' },
  { category: 'Site Cloning', name: 'Clone Parity Validation', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Validates clone matches original across visual, content, SEO, and functional dimensions with 100/100 parity scoring' },
  { category: 'Site Cloning', name: 'Clone Deployment Provisioning', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Provisions cloned sites to Vercel with domain assignment and DNS configuration' },
  { category: 'Site Cloning', name: 'Backend Reconstruction', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Analyzes frontend code to reconstruct backend API endpoints, data models, and business logic' },
  { category: 'Site Cloning', name: 'Clone Activity Tracking', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Per-clone activity log with stage, status, score, and metadata tracking' },
  { category: 'Site Cloning', name: 'Clone Library', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Persistent library of cloned sites with metadata and deployment status' },

  { category: 'Content Generation', name: 'SEO Tag Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Generates meta tags, Open Graph, Twitter cards, schema markup' },
  { category: 'Content Generation', name: 'Content Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'AI-powered page content generation with SEO optimization' },
  { category: 'Content Generation', name: 'Headline Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Multiple headline variants with A/B testing support' },
  { category: 'Content Generation', name: 'Copy Variants', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Generate multiple copy variations for different audiences' },
  { category: 'Content Generation', name: 'Social Content Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Platform-specific social media content generation' },
  { category: 'Content Generation', name: 'Email Sequence Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Multi-step email drip sequence generation' },
  { category: 'Content Generation', name: 'Before/After Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Visual before/after comparison content for conversions' },
  { category: 'Content Generation', name: 'Ad Creative Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Generate ad creatives with copy and visual directions' },
  { category: 'Content Generation', name: 'Video Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'AI video generation for marketing content' },
  { category: 'Content Generation', name: 'Logo Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'AI-powered logo generation' },
  { category: 'Content Generation', name: 'Brand Brief Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Generate comprehensive brand briefs' },
  { category: 'Content Generation', name: 'Rebrand Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Full rebrand with colors, fonts, messaging, and visual identity' },
  { category: 'Content Generation', name: 'Sitemap Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Generate XML sitemaps for SEO' },
  { category: 'Content Generation', name: 'Internal Link Builder', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'AI-powered internal link structure optimization' },
  { category: 'Content Generation', name: 'SEO Content Rewriter', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Rewrite content for SEO with keyword optimization' },
  { category: 'Content Generation', name: 'Keyword Clustering', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Cluster keywords into topical groups for content strategy' },
  { category: 'Content Generation', name: 'IndexNow Ping', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Instant index notification for search engines' },

  { category: 'Discovery & Research', name: 'Competitor Analysis', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Analyze competitor sites for strengths, weaknesses, and strategies' },
  { category: 'Discovery & Research', name: 'Top Performer Discovery', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Discover top-performing sites in a niche' },
  { category: 'Discovery & Research', name: 'Industry Knowledge Scraper', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Scrape industry-specific knowledge bases' },
  { category: 'Discovery & Research', name: 'Industry Pricing Scraper', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Scrape competitor pricing data' },
  { category: 'Discovery & Research', name: 'Tech News Scout', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Scout technology news for new tools and trends' },
  { category: 'Discovery & Research', name: 'Best Methods Research', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Research best practices and methods for any topic' },
  { category: 'Discovery & Research', name: 'Domain Availability Check', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Check domain availability and purchase' },
  { category: 'Discovery & Research', name: 'Domain Purchase', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Automated domain purchasing' },

  { category: 'Business Operations', name: 'Business Formation', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'LLC/Corp formation with legal document generation' },
  { category: 'Business Operations', name: 'Legal Document Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Generate contracts, terms, privacy policies, NDAs' },
  { category: 'Business Operations', name: 'Legal Signature Workflow', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'E-signature workflow with DocuSign integration' },
  { category: 'Business Operations', name: 'Quote Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Generate customer quotes with line items' },
  { category: 'Business Operations', name: 'Material Estimator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Construction/material estimation for service businesses' },
  { category: 'Business Operations', name: 'Formation Checkout', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Stripe-based business formation checkout flow' },

  { category: 'Lead Generation', name: 'Lead Capture', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Capture and score inbound leads' },
  { category: 'Lead Generation', name: 'Lead Scoring', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'AI-powered lead scoring with qualification criteria' },
  { category: 'Lead Generation', name: 'Outreach Drafter', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Draft personalized outreach emails' },
  { category: 'Lead Generation', name: 'Auto-Respond Lead', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Automated lead response with AI-generated replies' },

  { category: 'SEO/AEO', name: 'Technical SEO Audit', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Full technical SEO audit with Core Web Vitals, structured data, crawlability' },
  { category: 'SEO/AEO', name: 'Site Audit', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Comprehensive site audit with security, performance, SEO checks' },
  { category: 'SEO/AEO', name: 'CRO Audit', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Conversion rate optimization audit with A/B test recommendations' },
  { category: 'SEO/AEO', name: 'Security Scan', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Security vulnerability scanning with auto-fix' },

  { category: 'System Intelligence', name: 'System Name Generator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Generate system/product names with domain checking' },
  { category: 'System Intelligence', name: 'Autonomous System Validator', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Validates system integrity across all capabilities' },
  { category: 'System Intelligence', name: 'Self-Heal Deployment', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Auto-detect and fix deployment issues' },
  { category: 'System Intelligence', name: 'Self-Optimize Pipeline', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Autonomous pipeline optimization' },
  { category: 'System Intelligence', name: 'QA Gate', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Quality assurance gate with pass/fail criteria' },
  { category: 'System Intelligence', name: 'Run System Test', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'Execute system-level tests with scoring' },

  { category: 'Agents', name: 'Quality Agent', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'AI agent for quality assurance and testing' },
  { category: 'Agents', name: 'SEO/AEO Agent', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'AI agent for SEO and answer engine optimization' },
  { category: 'Agents', name: 'System Operator Agent', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'AI agent for system operations and maintenance' },
  { category: 'Agents', name: 'Tech Scout Agent', status: 'gap', score: 0, source: 'xtremeaibuilder', description: 'AI agent for technology scouting and research' },
];

// === CAPABILITIES FROM FAULT-LINE 3 ===
export const FAULTLINE_CAPABILITIES = [
  { category: 'Clone System', name: 'Xtreme Commander', status: 'gap', score: 0, source: 'faultline', description: 'Full-access AI commander for clone queue, studio, gallery, build, discovery, healing, security, media, books, CRM, and settings' },
  { category: 'Clone System', name: 'Clone Agent', status: 'gap', score: 0, source: 'faultline', description: 'Autonomous agent for site cloning with queue management' },
  { category: 'Clone System', name: 'Rebrand Agent', status: 'gap', score: 0, source: 'faultline', description: 'Agent for applying brand changes to cloned sites' },
  { category: 'Clone System', name: 'Clone Queue Management', status: 'gap', score: 0, source: 'faultline', description: 'Queue-based clone processing with retry and bulk operations' },
  { category: 'Clone System', name: 'Clone Parity Dashboard', status: 'gap', score: 0, source: 'faultline', description: 'Dashboard for tracking clone-to-original parity scores' },
  { category: 'Clone System', name: 'Visual Diff Tool', status: 'gap', score: 0, source: 'faultline', description: 'Side-by-side visual comparison with pixel diff' },
  { category: 'Clone System', name: 'Backend Capability Ledger', status: 'gap', score: 0, source: 'faultline', description: 'Tracks backend capabilities reconstructed from clones' },
  { category: 'Clone System', name: 'Canonical State Management', status: 'gap', score: 0, source: 'faultline', description: 'Canonical state tracking for clone synchronization' },
  { category: 'Clone System', name: 'Convergence Proof Log', status: 'gap', score: 0, source: 'faultline', description: 'Logs proving clone convergence to original' },

  { category: 'Build System', name: 'Fault-Line Builder', status: 'gap', score: 0, source: 'faultline', description: 'Autonomous website/app builder from specifications' },
  { category: 'Build System', name: 'Fault-Line Auto-Coder', status: 'gap', score: 0, source: 'faultline', description: 'AI-powered code generation and auto-fixing' },
  { category: 'Build System', name: 'Fault-Line Enhancer', status: 'gap', score: 0, source: 'faultline', description: 'Autonomous system enhancement and optimization' },
  { category: 'Build System', name: 'Build Queue', status: 'gap', score: 0, source: 'faultline', description: 'Queue-based build processing with priority' },
  { category: 'Build System', name: 'Generator Nodes', status: 'gap', score: 0, source: 'faultline', description: 'Modular generator system with versioned definitions' },
  { category: 'Build System', name: 'Launch Pipeline', status: 'gap', score: 0, source: 'faultline', description: 'End-to-end launch pipeline from build to deployment' },
  { category: 'Build System', name: 'Deployment Manifest', status: 'gap', score: 0, source: 'faultline', description: 'Deployment configuration tracking with rollback' },

  { category: 'QA & Testing', name: 'Fault-Line QA', status: 'gap', score: 0, source: 'faultline', description: 'Autonomous QA agent with test execution and scoring' },
  { category: 'QA & Testing', name: 'Fault-Line Sentinel', status: 'gap', score: 0, source: 'faultline', description: 'Monitoring sentinel for system health and alerts' },
  { category: 'QA & Testing', name: 'System Tester', status: 'gap', score: 0, source: 'faultline', description: 'Autonomous system testing with coverage tracking' },
  { category: 'QA & Testing', name: 'Auto-Fixer', status: 'gap', score: 0, source: 'faultline', description: 'Autonomous bug detection and fixing' },
  { category: 'QA & Testing', name: 'Coverage Ledger', status: 'gap', score: 0, source: 'faultline', description: 'Test coverage tracking across system components' },
  { category: 'QA & Testing', name: 'Gate Review', status: 'gap', score: 0, source: 'faultline', description: 'Quality gate reviews with approval workflow' },
  { category: 'QA & Testing', name: 'Master Quality Score', status: 'gap', score: 0, source: 'faultline', description: 'Aggregate quality scoring across all dimensions' },
  { category: 'QA & Testing', name: 'Playwright E2E Tests', status: 'gap', score: 0, source: 'faultline', description: 'Playwright-based end-to-end test suite' },
  { category: 'QA & Testing', name: 'Smoke Tests', status: 'gap', score: 0, source: 'faultline', description: 'Critical path smoke tests' },
  { category: 'QA & Testing', name: 'Recursive Audit', status: 'gap', score: 0, source: 'faultline', description: 'Recursive self-auditing script' },

  { category: 'Business Automation', name: 'Client Onboarding', status: 'gap', score: 0, source: 'faultline', description: 'Structured client onboarding with intake forms' },
  { category: 'Business Automation', name: 'Client Portal', status: 'gap', score: 0, source: 'faultline', description: 'Client-facing portal with project visibility' },
  { category: 'Business Automation', name: 'Client Success Score', status: 'gap', score: 0, source: 'faultline', description: 'Client success tracking and scoring' },
  { category: 'Business Automation', name: 'GHL Integration', status: 'gap', score: 0, source: 'faultline', description: 'GoHighLevel CRM integration with contacts, funnels, pipelines' },
  { category: 'Business Automation', name: 'Invoice Management', status: 'gap', score: 0, source: 'faultline', description: 'Invoice generation and tracking' },
  { category: 'Business Automation', name: 'Expense Tracking', status: 'gap', score: 0, source: 'faultline', description: 'Business expense tracking with categorization' },
  { category: 'Business Automation', name: 'Ledger Accounts', status: 'gap', score: 0, source: 'faultline', description: 'Double-entry ledger accounting' },
  { category: 'Business Automation', name: 'Cost of Business', status: 'gap', score: 0, source: 'faultline', description: 'Business cost analysis and optimization' },
  { category: 'Business Automation', name: 'Membership Management', status: 'gap', score: 0, source: 'faultline', description: 'Membership/subscription management' },
  { category: 'Business Automation', name: 'Cart & Orders', status: 'gap', score: 0, source: 'faultline', description: 'E-commerce cart and order management' },
  { category: 'Business Automation', name: 'Product Catalog', status: 'gap', score: 0, source: 'faultline', description: 'Product catalog with pricing profiles' },
  { category: 'Business Automation', name: 'Pricing Rules Engine', status: 'gap', score: 0, source: 'faultline', description: 'Dynamic pricing rules with market price tracking' },
  { category: 'Business Automation', name: 'Multi-Site Management', status: 'gap', score: 0, source: 'faultline', description: 'Manage multiple sites/locations from one dashboard' },

  { category: 'Compliance & Legal', name: 'Asset Licensing', status: 'gap', score: 0, source: 'faultline', description: 'Digital asset license tracking and management' },
  { category: 'Compliance & Legal', name: 'Consent Records', status: 'gap', score: 0, source: 'faultline', description: 'GDPR consent tracking and management' },
  { category: 'Compliance & Legal', name: 'Exclusion Records', status: 'gap', score: 0, source: 'faultline', description: 'Data exclusion and suppression lists' },
  { category: 'Compliance & Legal', name: 'Envato Asset Management', status: 'gap', score: 0, source: 'faultline', description: 'Envato marketplace asset tracking with taxonomy' },
  { category: 'Compliance & Legal', name: 'Audit Templates', status: 'gap', score: 0, source: 'faultline', description: 'Reusable audit templates with findings' },

  { category: 'Monitoring', name: 'Monitoring Rules', status: 'gap', score: 0, source: 'faultline', description: 'Configurable monitoring rules with thresholds' },
  { category: 'Monitoring', name: 'Monitoring Events', status: 'gap', score: 0, source: 'faultline', description: 'Event-driven monitoring with alerting' },
  { category: 'Monitoring', name: 'Heartbeat Receipts', status: 'gap', score: 0, source: 'faultline', description: 'System heartbeat tracking with receipts' },
  { category: 'Monitoring', name: 'Overnight Execution Receipts', status: 'gap', score: 0, source: 'faultline', description: 'Overnight autonomous execution tracking' },
  { category: 'Monitoring', name: 'Partner API Keys', status: 'gap', score: 0, source: 'faultline', description: 'Partner API key management for external integrations' },

  { category: 'Intelligence', name: 'Industry Opportunity Detection', status: 'gap', score: 0, source: 'faultline', description: 'Detect business opportunities by industry' },
  { category: 'Intelligence', name: 'Interaction Graph', status: 'gap', score: 0, source: 'faultline', description: 'Graph-based interaction analysis' },
  { category: 'Intelligence', name: 'Environment Profiles', status: 'gap', score: 0, source: 'faultline', description: 'Environment-specific configuration profiles' },
  { category: 'Intelligence', name: 'Browser Provider Registry', status: 'gap', score: 0, source: 'faultline', description: 'Registry of browser automation providers for comparison' },
];

// === CAPABILITIES FROM VISION CORTEX ===
export const VISIONCORTEX_CAPABILITIES = [
  { category: 'System Analysis', name: 'Deep System Audit (5-Dimension)', status: 'gap', score: 0, source: 'visioncortex', description: 'Autonomous 5-dimension audit: performance, SEO, security, accessibility, content — with live web context and perfection prompts' },
  { category: 'System Analysis', name: 'Master System Analysis', status: 'gap', score: 0, source: 'visioncortex', description: 'Comprehensive system analysis with benchmark identification and competitor research' },
  { category: 'System Analysis', name: 'System DNA Scoring', status: 'gap', score: 0, source: 'visioncortex', description: 'DNA-based multi-score model with critical failure detection — aggregate never hides a critical gap' },
  { category: 'System Analysis', name: 'DNA Gap Engine', status: 'gap', score: 0, source: 'visioncortex', description: 'Autonomous gap detection between current state and 100% perfection' },
  { category: 'System Analysis', name: 'DNA Self-Heal', status: 'gap', score: 0, source: 'visioncortex', description: 'Autonomous self-healing based on DNA gap analysis' },
  { category: 'System Analysis', name: 'DNA Traceability', status: 'gap', score: 0, source: 'visioncortex', description: 'Full traceability from requirement → capability → gap → fix' },
  { category: 'System Analysis', name: 'System Perfection Cycle', status: 'gap', score: 0, source: 'visioncortex', description: 'Autonomous cycle that brings each dimension from current score to 100%' },
  { category: 'System Analysis', name: 'Perfection Report Generator', status: 'gap', score: 0, source: 'visioncortex', description: 'Generates zero-ambiguity perfection prompts for each dimension' },
  { category: 'System Analysis', name: 'Forensic Audit', status: 'gap', score: 0, source: 'visioncortex', description: 'Deep forensic audit with evidence artifacts' },
  { category: 'System Analysis', name: 'External Site Audit', status: 'gap', score: 0, source: 'visioncortex', description: 'Audit any external site via Cloud Browser browsing' },
  { category: 'System Analysis', name: 'Daily Site Audit', status: 'gap', score: 0, source: 'visioncortex', description: 'Scheduled daily site audits with trend tracking' },
  { category: 'System Analysis', name: 'System Analyst', status: 'gap', score: 0, source: 'visioncortex', description: 'Autonomous system analyst agent' },

  { category: 'AI Council', name: 'Council Session', status: 'gap', score: 0, source: 'visioncortex', description: 'Multi-agent council session with debate and consensus' },
  { category: 'AI Council', name: 'Council Blueprint', status: 'gap', score: 0, source: 'visioncortex', description: 'Council-generated strategic blueprints' },
  { category: 'AI Council', name: 'Council Predict', status: 'gap', score: 0, source: 'visioncortex', description: 'Council-based outcome prediction' },
  { category: 'AI Council', name: 'Council Compound', status: 'gap', score: 0, source: 'visioncortex', description: 'Compound intelligence from multiple agent perspectives' },
  { category: 'AI Council', name: 'Council Site Audit', status: 'gap', score: 0, source: 'visioncortex', description: 'Council-based site audit with multiple expert perspectives' },
  { category: 'AI Council', name: 'Agent Debate', status: 'gap', score: 0, source: 'visioncortex', description: 'Structured agent debates with argumentation' },
  { category: 'AI Council', name: 'Monthly Award Ceremony', status: 'gap', score: 0, source: 'visioncortex', description: 'Agent performance awards and recognition' },

  { category: 'Shadow Mode', name: 'Shadow Browse', status: 'gap', score: 0, source: 'visioncortex', description: 'Stealth browsing for reconnaissance without detection' },
  { category: 'Shadow Mode', name: 'Shadow Clone', status: 'gap', score: 0, source: 'visioncortex', description: 'Stealth cloning without triggering bot detection' },
  { category: 'Shadow Mode', name: 'Shadow Build Strategy', status: 'gap', score: 0, source: 'visioncortex', description: 'Strategic shadow building with competitive analysis' },
  { category: 'Shadow Mode', name: 'Shadow Forcefield', status: 'gap', score: 0, source: 'visioncortex', description: 'Protective shadow mode with anti-detection forcefield' },
  { category: 'Shadow Mode', name: 'Shadow Money Hunt', status: 'gap', score: 0, source: 'visioncortex', description: 'Autonomous revenue opportunity discovery' },
  { category: 'Shadow Mode', name: 'Shadow Revenue Check', status: 'gap', score: 0, source: 'visioncortex', description: 'Revenue verification and tracking' },
  { category: 'Shadow Mode', name: 'Shadow Sentiment', status: 'gap', score: 0, source: 'visioncortex', description: 'Sentiment analysis during shadow operations' },
  { category: 'Shadow Mode', name: 'Shadow Performance Log', status: 'gap', score: 0, source: 'visioncortex', description: 'Performance tracking during shadow operations' },
  { category: 'Shadow Mode', name: 'Shadow Save to Drive', status: 'gap', score: 0, source: 'visioncortex', description: 'Save shadow operation results to Google Drive' },
  { category: 'Shadow Mode', name: 'Shadow Schedule Milestones', status: 'gap', score: 0, source: 'visioncortex', description: 'Schedule milestones for shadow operations' },
  { category: 'Shadow Mode', name: 'Shadow Create Stripe Products', status: 'gap', score: 0, source: 'visioncortex', description: 'Create Stripe products from shadow research' },

  { category: 'Factory System', name: 'Factory Seed Generator', status: 'gap', score: 0, source: 'visioncortex', description: 'Generate factory seed projects from specifications' },
  { category: 'Factory System', name: 'Factory Brand Generator', status: 'gap', score: 0, source: 'visioncortex', description: 'Generate complete brand packages' },
  { category: 'Factory System', name: 'Factory Brand Pack', status: 'gap', score: 0, source: 'visioncortex', description: 'Complete brand pack with logo, colors, fonts, messaging' },
  { category: 'Factory System', name: 'Factory Content Generator', status: 'gap', score: 0, source: 'visioncortex', description: 'Generate content for factory projects' },
  { category: 'Factory System', name: 'Factory Domain Generator', status: 'gap', score: 0, source: 'visioncortex', description: 'Generate and check domain names' },
  { category: 'Factory System', name: 'Factory Growth OS', status: 'gap', score: 0, source: 'visioncortex', description: 'Complete growth operating system generation' },
  { category: 'Factory System', name: 'Factory Research Industry', status: 'gap', score: 0, source: 'visioncortex', description: 'Industry research for factory projects' },
  { category: 'Factory System', name: 'Factory Social AI', status: 'gap', score: 0, source: 'visioncortex', description: 'Social media AI content generation' },
  { category: 'Factory System', name: 'Factory Website Generator', status: 'gap', score: 0, source: 'visioncortex', description: 'Full website generation from factory specs' },
  { category: 'Factory System', name: 'Build Pack Generator', status: 'gap', score: 0, source: 'visioncortex', description: 'Complete build pack with all project assets' },

  { category: 'Opportunity Intelligence', name: 'Opportunity Sweep', status: 'gap', score: 0, source: 'visioncortex', description: 'Autonomous opportunity scanning and discovery' },
  { category: 'Opportunity Intelligence', name: 'Opportunity Research', status: 'gap', score: 0, source: 'visioncortex', description: 'Deep research on identified opportunities' },
  { category: 'Opportunity Intelligence', name: 'Opportunity Follow-Up', status: 'gap', score: 0, source: 'visioncortex', description: 'Automated opportunity follow-up tracking' },
  { category: 'Opportunity Intelligence', name: 'Opportunity Respond', status: 'gap', score: 0, source: 'visioncortex', description: 'Automated response to opportunities' },
  { category: 'Opportunity Intelligence', name: 'Intel Feed', status: 'gap', score: 0, source: 'visioncortex', description: 'Real-time intelligence feed ingestion' },
  { category: 'Opportunity Intelligence', name: 'Ingest Intel', status: 'gap', score: 0, source: 'visioncortex', description: 'Intelligence data ingestion pipeline' },
  { category: 'Opportunity Intelligence', name: 'Cloud Browser Intel', status: 'gap', score: 0, source: 'visioncortex', description: 'Browser-based intelligence gathering' },

  { category: 'Life Simulation', name: 'Simulate Life', status: 'gap', score: 0, source: 'visioncortex', description: 'Life outcome simulation with decision modeling' },
  { category: 'Life Simulation', name: 'Simulate Outcomes', status: 'gap', score: 0, source: 'visioncortex', description: 'Outcome simulation for decisions' },
  { category: 'Life Simulation', name: 'Simulate Strategy', status: 'gap', score: 0, source: 'visioncortex', description: 'Strategy simulation and comparison' },
  { category: 'Life Simulation', name: 'Simulate User Journey', status: 'gap', score: 0, source: 'visioncortex', description: 'User journey simulation for UX optimization' },
  { category: 'Life Simulation', name: 'Life Choice Generator', status: 'gap', score: 0, source: 'visioncortex', description: 'Generate life choices with consequence analysis' },
  { category: 'Life Simulation', name: 'Life Plan Lock', status: 'gap', score: 0, source: 'visioncortex', description: 'Lock life plans with commitment tracking' },
  { category: 'Life Simulation', name: 'Detect Life Drift', status: 'gap', score: 0, source: 'visioncortex', description: 'Detect drift from locked life plans' },
  { category: 'Life Simulation', name: 'Track Reality', status: 'gap', score: 0, source: 'visioncortex', description: 'Track reality vs. simulation divergence' },

  { category: 'Enhancement Engine', name: 'Auto-Recommend', status: 'gap', score: 0, source: 'visioncortex', description: 'Autonomous enhancement recommendations with priority' },
  { category: 'Enhancement Engine', name: 'Auto-Recommend All Systems', status: 'gap', score: 0, source: 'visioncortex', description: 'System-wide enhancement recommendations' },
  { category: 'Enhancement Engine', name: 'Auto-Enhance All', status: 'gap', score: 0, source: 'visioncortex', description: 'Autonomous enhancement execution across all systems' },
  { category: 'Enhancement Engine', name: 'Enhancement Approver', status: 'gap', score: 0, source: 'visioncortex', description: 'Approval workflow for system enhancements' },
  { category: 'Enhancement Engine', name: 'Implement Enhancement', status: 'gap', score: 0, source: 'visioncortex', description: 'Execute approved enhancements with tracking' },
  { category: 'Enhancement Engine', name: 'Run Enhancement Cycle', status: 'gap', score: 0, source: 'visioncortex', description: 'Full enhancement cycle from detection to implementation' },
  { category: 'Enhancement Engine', name: 'Gap Recommender', status: 'gap', score: 0, source: 'visioncortex', description: 'AI-powered gap analysis with actionable recommendations' },
  { category: 'Enhancement Engine', name: 'Generate Strategies', status: 'gap', score: 0, source: 'visioncortex', description: 'Generate multiple strategic approaches for closing gaps' },

  { category: 'Agents (Vision Cortex)', name: 'Vision Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Strategic vision and direction agent' },
  { category: 'Agents (Vision Cortex)', name: 'Shadow Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Stealth operations and reconnaissance agent' },
  { category: 'Agents (Vision Cortex)', name: 'Strategy Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Strategic planning and execution agent' },
  { category: 'Agents (Vision Cortex)', name: 'Validator Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Validation and verification agent' },
  { category: 'Agents (Vision Cortex)', name: 'Quant Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Quantitative analysis agent' },
  { category: 'Agents (Vision Cortex)', name: 'Sage Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Wisdom and long-term thinking agent' },
  { category: 'Agents (Vision Cortex)', name: 'Philosopher Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Deep reasoning and ethics agent' },
  { category: 'Agents (Vision Cortex)', name: 'Capital Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Capital allocation and financial agent' },
  { category: 'Agents (Vision Cortex)', name: 'Treasurer Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Treasury and financial management agent' },
  { category: 'Agents (Vision Cortex)', name: 'Distributor Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Distribution and logistics agent' },
  { category: 'Agents (Vision Cortex)', name: 'Brand Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Brand strategy and identity agent' },
  { category: 'Agents (Vision Cortex)', name: 'Documenter Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Documentation and knowledge capture agent' },
  { category: 'Agents (Vision Cortex)', name: 'Maxwell Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Personal coaching and development agent' },
  { category: 'Agents (Vision Cortex)', name: 'Personal Coach Agent', status: 'gap', score: 0, source: 'visioncortex', description: 'Personal coaching with life plan integration' },
  { category: 'Agents (Vision Cortex)', name: 'Autonomous Builder', status: 'gap', score: 0, source: 'visioncortex', description: 'Fully autonomous building agent with dispatch capability' },

  { category: 'Deployment & Provisioning', name: 'Provision Supabase', status: 'gap', score: 0, source: 'visioncortex', description: 'Automated Supabase project provisioning' },
  { category: 'Deployment & Provisioning', name: 'Provision Vercel', status: 'gap', score: 0, source: 'visioncortex', description: 'Automated Vercel project provisioning' },
  { category: 'Deployment & Provisioning', name: 'Pipeline Orchestrator', status: 'gap', score: 0, source: 'visioncortex', description: 'End-to-end pipeline orchestration' },
  { category: 'Deployment & Provisioning', name: 'Nightly Pipeline Prep', status: 'gap', score: 0, source: 'visioncortex', description: 'Nightly pipeline preparation and scheduling' },
  { category: 'Deployment & Provisioning', name: 'Launch Pipeline Build', status: 'gap', score: 0, source: 'visioncortex', description: 'Build launch pipelines from specifications' },
  { category: 'Deployment & Provisioning', name: 'Dispatch to Builder', status: 'gap', score: 0, source: 'visioncortex', description: 'Dispatch tasks to autonomous builder agents' },

  { category: 'Search & SEO', name: 'Search Console Sync', status: 'gap', score: 0, source: 'visioncortex', description: 'Google Search Console data synchronization' },
  { category: 'Search & SEO', name: 'Search Console Metrics', status: 'gap', score: 0, source: 'visioncortex', description: 'Search Console metrics tracking and analysis' },
  { category: 'Search & SEO', name: 'Calendar Roadmap', status: 'gap', score: 0, source: 'visioncortex', description: 'SEO roadmap with calendar integration' },
  { category: 'Search & SEO', name: 'Run Marketer', status: 'gap', score: 0, source: 'visioncortex', description: 'Autonomous marketing agent' },

  { category: 'Onboarding', name: 'Onboarding Quest', status: 'gap', score: 0, source: 'visioncortex', description: 'Gamified onboarding with quest progression' },
  { category: 'Onboarding', name: 'Personal Onboarding', status: 'gap', score: 0, source: 'visioncortex', description: 'Personalized onboarding experience' },
  { category: 'Onboarding', name: 'Owner Digest', status: 'gap', score: 0, source: 'visioncortex', description: 'Daily owner digest with system status' },
  { category: 'Onboarding', name: 'ReguShield', status: 'gap', score: 0, source: 'visioncortex', description: 'Regulatory compliance shield' },
  { category: 'Onboarding', name: 'Sync Project Brain', status: 'gap', score: 0, source: 'visioncortex', description: 'Synchronize project knowledge across systems' },
];

// === ALL POSSIBLE CAPABILITIES FOR A BROWSER AUTOMATION SYSTEM ===
export const ALL_POSSIBLE_CAPABILITIES = [
  // Infrastructure
  { category: 'Infrastructure', name: 'Distributed Browser Grid', status: 'gap', score: 0, description: 'Globally distributed browser nodes with edge computing' },
  { category: 'Infrastructure', name: 'Kubernetes Orchestration', status: 'gap', score: 0, description: 'K8s-managed browser pods with auto-scaling' },
  { category: 'Infrastructure', name: 'Serverless Browser Functions', status: 'gap', score: 0, description: 'On-demand serverless browser execution' },
  { category: 'Infrastructure', name: 'Multi-Cloud Support', status: 'gap', score: 0, description: 'AWS, GCP, Azure, Railway deployment support' },
  { category: 'Infrastructure', name: 'GPU Acceleration', status: 'gap', score: 0, description: 'GPU-accelerated rendering for WebGL/WebGPU sites' },
  { category: 'Infrastructure', name: 'Edge Caching', status: 'gap', score: 0, description: 'CDN-level edge caching for browser assets' },
  { category: 'Infrastructure', name: 'Session Affinity', status: 'gap', score: 0, description: 'Sticky session routing for stateful workloads' },
  { category: 'Infrastructure', name: 'Zero-Downtime Deploys', status: 'gap', score: 0, description: 'Blue-green deployments with no session interruption' },
  { category: 'Infrastructure', name: 'WebSocket Proxy', status: 'gap', score: 0, description: 'WebSocket connection proxying for real-time sites' },
  { category: 'Infrastructure', name: 'Browser Isolation Sandboxes', status: 'gap', score: 0, description: 'OS-level browser isolation for security' },
  { category: 'Infrastructure', name: 'Custom Browser Builds', status: 'gap', score: 0, description: 'Custom Chromium/Firefox builds with patches' },
  { category: 'Infrastructure', name: 'Mobile Device Farm', status: 'gap', score: 0, description: 'Real mobile devices for mobile browser testing' },
  { category: 'Infrastructure', name: 'Load Balancing', status: 'gap', score: 0, description: 'Intelligent load balancing across browser nodes' },
  { category: 'Infrastructure', name: 'Graceful Degradation', status: 'gap', score: 0, description: 'Fallback rendering modes for degraded conditions' },

  // Anti-Detection
  { category: 'Anti-Detection', name: 'ML-Based Bot Detection Bypass', status: 'gap', score: 0, description: 'Machine learning models to evade advanced bot detection' },
  { category: 'Anti-Detection', name: 'Canvas/WebGL Spoofing', status: 'gap', score: 0, description: 'Hardware-accelerated canvas/WebGL fingerprint spoofing' },
  { category: 'Anti-Detection', name: 'AudioContext Fingerprint', status: 'gap', score: 0, description: 'AudioContext fingerprint randomization' },
  { category: 'Anti-Detection', name: 'Font Fingerprinting', status: 'gap', score: 0, description: 'Font enumeration fingerprint protection' },
  { category: 'Anti-Detection', name: 'WebRTC IP Leak Prevention', status: 'gap', score: 0, description: 'WebRTC local IP leak prevention' },
  { category: 'Anti-Detection', name: 'Behavioral Biometrics', status: 'gap', score: 0, description: 'Human-like mouse/keyboard behavioral biometrics' },
  { category: 'Anti-Detection', name: 'Headless Detection Bypass', status: 'gap', score: 0, description: 'Comprehensive headless Chrome detection bypass' },
  { category: 'Anti-Detection', name: 'Navigator Properties Spoofing', status: 'gap', score: 0, description: 'Complete navigator object property spoofing' },
  { category: 'Anti-Detection', name: 'Plugin/MimeType Spoofing', status: 'gap', score: 0, description: 'Realistic plugin and mimetype emulation' },
  { category: 'Anti-Detection', name: 'Screen Resolution Spoofing', status: 'gap', score: 0, description: 'Screen resolution and color depth spoofing' },
  { category: 'Anti-Detection', name: 'Battery API Spoofing', status: 'gap', score: 0, description: 'Battery status API fingerprint protection' },
  { category: 'Anti-Detection', name: 'Speech Synthesis Spoofing', status: 'gap', score: 0, description: 'Speech synthesis API voice fingerprint protection' },
  { category: 'Anti-Detection', name: 'Timing Attack Protection', status: 'gap', score: 0, description: 'High-resolution timing attack prevention' },
  { category: 'Anti-Detection', name: 'Device Memory Spoofing', status: 'gap', score: 0, description: 'Device memory and hardware concurrency spoofing' },

  // CAPTCHA
  { category: 'CAPTCHA', name: 'reCAPTCHA v3 Solver', status: 'gap', score: 0, description: 'Score-based reCAPTCHA v3 solver' },
  { category: 'CAPTCHA', name: 'reCAPTCHA Enterprise Solver', status: 'gap', score: 0, description: 'Enterprise-grade reCAPTCHA solver' },
  { category: 'CAPTCHA', name: 'Funcaptcha Solver', status: 'gap', score: 0, description: 'Arkose Labs Funcaptcha solver' },
  { category: 'CAPTCHA', name: 'Geetest Solver', status: 'gap', score: 0, description: 'Geetest slider and click captcha solver' },
  { category: 'CAPTCHA', name: 'Image Classification Solver', status: 'gap', score: 0, description: 'ML-based image classification for any captcha type' },
  { category: 'CAPTCHA', name: 'Text CAPTCHA OCR', status: 'gap', score: 0, description: 'OCR-based text captcha solver' },
  { category: 'CAPTCHA', name: 'Math CAPTCHA Solver', status: 'gap', score: 0, description: 'Math problem captcha solver' },
  { category: 'CAPTCHA', name: 'Slider CAPTCHA Solver', status: 'gap', score: 0, description: 'Slider puzzle captcha solver with trajectory simulation' },
  { category: 'CAPTCHA', name: 'Multi-Provider Fallback Chain', status: 'gap', score: 0, description: 'Chain of captcha providers with automatic fallback' },

  // Data Extraction
  { category: 'Data Extraction', name: 'Structured Data Extraction (Schema.org)', status: 'gap', score: 0, description: 'Extract and parse schema.org structured data' },
  { category: 'Data Extraction', name: 'JavaScript-Rendered Content', status: 'gap', score: 0, description: 'Extract content from JS-rendered SPAs' },
  { category: 'Data Extraction', name: 'Infinite Scroll Extraction', status: 'gap', score: 0, description: 'Extract data from infinite-scroll pages' },
  { category: 'Data Extraction', name: 'Lazy-Load Image Extraction', status: 'gap', score: 0, description: 'Extract lazy-loaded images after triggering load' },
  { category: 'Data Extraction', name: 'iframe Content Extraction', status: 'gap', score: 0, description: 'Extract content from nested iframes' },
  { category: 'Data Extraction', name: 'Shadow DOM Extraction', status: 'gap', score: 0, description: 'Extract content from shadow DOM elements' },
  { category: 'Data Extraction', name: 'Dynamic Table Extraction', status: 'gap', score: 0, description: 'Extract tables with dynamic row/column structure' },
  { category: 'Data Extraction', name: 'File Download Extraction', status: 'gap', score: 0, description: 'Download and parse files (PDF, CSV, XLSX) from pages' },
  { category: 'Data Extraction', name: 'API Response Interception', status: 'gap', score: 0, description: 'Intercept and parse XHR/fetch API responses' },
  { category: 'Data Extraction', name: 'WebSocket Message Capture', status: 'gap', score: 0, description: 'Capture WebSocket messages for real-time data' },
  { category: 'Data Extraction', name: 'OCR Text Extraction', status: 'gap', score: 0, description: 'OCR text extraction from images and screenshots' },
  { category: 'Data Extraction', name: 'Video/Audio Transcription', status: 'gap', score: 0, description: 'Transcribe video and audio content from pages' },
  { category: 'Data Extraction', name: 'Form Auto-Fill', status: 'gap', score: 0, description: 'Intelligent form auto-fill with field type detection' },
  { category: 'Data Extraction', name: 'Multi-Page Form Wizard', status: 'gap', score: 0, description: 'Navigate multi-step form wizards automatically' },
  { category: 'Data Extraction', name: 'Email/Phone Extraction', status: 'gap', score: 0, description: 'Extract email addresses and phone numbers from pages' },
  { category: 'Data Extraction', name: 'Social Media Profile Extraction', status: 'gap', score: 0, description: 'Extract social media profiles and posts' },
  { category: 'Data Extraction', name: 'E-commerce Product Extraction', status: 'gap', score: 0, description: 'Extract product data: name, price, reviews, specs' },
  { category: 'Data Extraction', name: 'Real Estate Listing Extraction', status: 'gap', score: 0, description: 'Extract real estate listings with photos and details' },
  { category: 'Data Extraction', name: 'Job Posting Extraction', status: 'gap', score: 0, description: 'Extract job postings with requirements and salaries' },
  { category: 'Data Extraction', name: 'News Article Extraction', status: 'gap', score: 0, description: 'Extract news articles with full body text and metadata' },

  // AI & Intelligence
  { category: 'AI & Intelligence', name: 'Natural Language Automation', status: 'gap', score: 0, description: 'Convert natural language instructions to automation steps' },
  { category: 'AI & Intelligence', name: 'Visual Element Recognition', status: 'gap', score: 0, description: 'AI-powered visual element identification without selectors' },
  { category: 'AI & Intelligence', name: 'Page Intent Understanding', status: 'gap', score: 0, description: 'Understand page purpose and intent for smart extraction' },
  { category: 'AI & Intelligence', name: 'Auto-Generated Selectors', status: 'gap', score: 0, description: 'AI generates robust selectors from element descriptions' },
  { category: 'AI & Intelligence', name: 'Content Classification', status: 'gap', score: 0, description: 'Automatically classify extracted content by type' },
  { category: 'AI & Intelligence', name: 'Sentiment Analysis', status: 'gap', score: 0, description: 'Analyze sentiment of extracted text content' },
  { category: 'AI & Intelligence', name: 'Entity Recognition (NER)', status: 'gap', score: 0, description: 'Named entity recognition in extracted content' },
  { category: 'AI & Intelligence', name: 'Language Detection', status: 'gap', score: 0, description: 'Automatic language detection and translation' },
  { category: 'AI & Intelligence', name: 'Summarization', status: 'gap', score: 0, description: 'Automatic content summarization' },
  { category: 'AI & Intelligence', name: 'Data Validation & Cleaning', status: 'gap', score: 0, description: 'AI-powered data validation and cleaning' },
  { category: 'AI & Intelligence', name: 'Smart Retry Strategy', status: 'gap', score: 0, description: 'AI determines optimal retry strategy per error type' },
  { category: 'AI & Intelligence', name: 'Predictive Failure Detection', status: 'gap', score: 0, description: 'Predict job failures before they happen' },
  { category: 'AI & Intelligence', name: 'Auto-Healing Workflows', status: 'gap', score: 0, description: 'Automatically repair broken automation workflows' },
  { category: 'AI & Intelligence', name: 'Multi-Modal Extraction', status: 'gap', score: 0, description: 'Extract data from text, images, video, and audio simultaneously' },
  { category: 'AI & Intelligence', name: 'Knowledge Graph Construction', status: 'gap', score: 0, description: 'Build knowledge graphs from extracted data' },
  { category: 'AI & Intelligence', name: 'Competitive Intelligence', status: 'gap', score: 0, description: 'Automated competitive intelligence gathering' },
  { category: 'AI & Intelligence', name: 'Market Research Automation', status: 'gap', score: 0, description: 'Automated market research with trend analysis' },
  { category: 'AI & Intelligence', name: 'Price Monitoring', status: 'gap', score: 0, description: 'Continuous price monitoring across competitors' },
  { category: 'AI & Intelligence', name: 'Review Aggregation', status: 'gap', score: 0, description: 'Aggregate and analyze reviews from multiple sources' },
  { category: 'AI & Intelligence', name: 'Social Listening', status: 'gap', score: 0, description: 'Social media monitoring and sentiment tracking' },

  // Security & Compliance
  { category: 'Security & Compliance', name: 'SOC 2 Type II Compliance', status: 'gap', score: 0, description: 'Full SOC 2 Type II compliance with audit support' },
  { category: 'Security & Compliance', name: 'HIPAA Compliance', status: 'gap', score: 0, description: 'HIPAA-compliant data handling for healthcare' },
  { category: 'Security & Compliance', name: 'GDPR Data Portability', status: 'gap', score: 0, description: 'GDPR data export and portability features' },
  { category: 'Security & Compliance', name: 'PCI-DSS Compliance', status: 'gap', score: 0, description: 'PCI-DSS compliant payment data handling' },
  { category: 'Security & Compliance', name: 'Data Residency Controls', status: 'gap', score: 0, description: 'Geographic data residency enforcement' },
  { category: 'Security & Compliance', name: 'Encryption at Rest', status: 'gap', score: 0, description: 'Full encryption at rest for all stored data' },
  { category: 'Security & Compliance', name: 'Tokenization', status: 'gap', score: 0, description: 'Tokenize sensitive data for safe storage' },
  { category: 'Security & Compliance', name: 'Audit Trail Export', status: 'gap', score: 0, description: 'Exportable audit trails for compliance' },
  { category: 'Security & Compliance', name: 'Penetration Testing Suite', status: 'gap', score: 0, description: 'Built-in penetration testing capabilities' },
  { category: 'Security & Compliance', name: 'Vulnerability Scanning', status: 'gap', score: 0, description: 'Automated vulnerability scanning of extracted data' },
  { category: 'Security & Compliance', name: 'Secret Scanning', status: 'gap', score: 0, description: 'Scan extracted content for exposed secrets' },
  { category: 'Security & Compliance', name: 'Data Loss Prevention', status: 'gap', score: 0, description: 'DLP policies for extracted data' },
  { category: 'Security & Compliance', name: 'Content Security Policy', status: 'gap', score: 0, description: 'CSP enforcement for browser sessions' },
  { category: 'Security & Compliance', name: 'Zero Trust Architecture', status: 'gap', score: 0, description: 'Zero trust security model implementation' },

  // Performance & Scale
  { category: 'Performance & Scale', name: 'Horizontal Pod Autoscaling', status: 'gap', score: 0, description: 'HPA-based autoscaling with custom metrics' },
  { category: 'Performance & Scale', name: 'Request Concurrency', status: 'gap', score: 0, description: 'High-concurrency request handling per session' },
  { category: 'Performance & Scale', name: 'Connection Pooling', status: 'gap', score: 0, description: 'Database and HTTP connection pooling' },
  { category: 'Performance & Scale', name: 'Resource Quotas', status: 'gap', score: 0, description: 'Per-tenant resource quotas and limits' },
  { category: 'Performance & Scale', name: 'Priority Queueing', status: 'gap', score: 0, description: 'Multi-level priority queue with fair scheduling' },
  { category: 'Performance & Scale', name: 'Batch Processing', status: 'gap', score: 0, description: 'Batch job processing for efficiency' },
  { category: 'Performance & Scale', name: 'Stream Processing', status: 'gap', score: 0, description: 'Real-time stream processing of extraction results' },
  { category: 'Performance & Scale', name: 'Distributed Tracing', status: 'gap', score: 0, description: 'OpenTelemetry distributed tracing' },
  { category: 'Performance & Scale', name: 'Custom Metrics', status: 'gap', score: 0, description: 'Custom business metrics and KPIs' },
  { category: 'Performance & Scale', name: 'SLA Monitoring', status: 'gap', score: 0, description: 'SLA monitoring with alerting' },
  { category: 'Performance & Scale', name: 'Chaos Engineering', status: 'gap', score: 0, description: 'Chaos testing for resilience validation' },
  { category: 'Performance & Scale', name: 'Circuit Breakers', status: 'gap', score: 0, description: 'Circuit breaker pattern for external calls' },
  { category: 'Performance & Scale', name: 'Bulkhead Isolation', status: 'gap', score: 0, description: 'Bulkhead pattern for resource isolation' },
  { category: 'Performance & Scale', name: 'Rate Limit Per Endpoint', status: 'gap', score: 0, description: 'Per-endpoint rate limiting with burst support' },

  // Developer Experience
  { category: 'Developer Experience', name: 'REST API', status: 'implemented', score: 85, description: 'Full REST API with OpenAPI documentation' },
  { category: 'Developer Experience', name: 'GraphQL API', status: 'gap', score: 0, description: 'GraphQL API for flexible queries' },
  { category: 'Developer Experience', name: 'WebSocket API', status: 'gap', score: 0, description: 'Real-time WebSocket API for live updates' },
  { category: 'Developer Experience', name: 'gRPC API', status: 'gap', score: 0, description: 'High-performance gRPC API' },
  { category: 'Developer Experience', name: 'Python SDK', status: 'implemented', score: 82, description: 'Python SDK for API interactions' },
  { category: 'Developer Experience', name: 'JavaScript/TypeScript SDK', status: 'gap', score: 0, description: 'JS/TS SDK for API interactions' },
  { category: 'Developer Experience', name: 'Go SDK', status: 'gap', score: 0, description: 'Go SDK for API interactions' },
  { category: 'Developer Experience', name: 'Java SDK', status: 'gap', score: 0, description: 'Java SDK for API interactions' },
  { category: 'Developer Experience', name: 'CLI Tool', status: 'gap', score: 0, description: 'Command-line interface for automation' },
  { category: 'Developer Experience', name: 'VS Code Extension', status: 'gap', score: 0, description: 'VS Code extension for job development' },
  { category: 'Developer Experience', name: 'Postman Collection', status: 'gap', score: 0, description: 'Pre-built Postman collection for API testing' },
  { category: 'Developer Experience', name: 'Webhook Subscriptions', status: 'implemented', score: 85, description: 'Webhook event subscriptions' },
  { category: 'Developer Experience', name: 'MCP Server', status: 'implemented', score: 78, description: 'MCP server for AI client integration' },
  { category: 'Developer Experience', name: 'Sandbox Environment', status: 'implemented', score: 80, description: 'Sandbox environment for testing' },
  { category: 'Developer Experience', name: 'API Versioning', status: 'gap', score: 0, description: 'API versioning with backward compatibility' },
  { category: 'Developer Experience', name: 'Interactive API Explorer', status: 'gap', score: 0, description: 'In-browser API explorer with try-it functionality' },
];

// === GAPS ANALYSIS ===
export const GAP_ANALYSIS = [
  { gap: 'No site cloning engine', severity: 'critical', category: 'Site Cloning', recommendation: 'Integrate cloneFullSite from Xtreme AI Builder — renders target, extracts HTML/metadata/links/images, discovers pages from sitemap', closable: true, source: 'xtremeaibuilder' },
  { gap: 'No visual clone comparison', severity: 'critical', category: 'Site Cloning', recommendation: 'Integrate Vision Cortex Compare for pixel-level diff between original and clone', closable: true, source: 'xtremeaibuilder' },
  { gap: 'No Design DNA extraction', severity: 'high', category: 'Site Cloning', recommendation: 'Integrate extractDesignDNA to capture colors, fonts, spacing, layout from target sites', closable: true, source: 'xtremeaibuilder' },
  { gap: 'No clone parity validation', severity: 'high', category: 'Site Cloning', recommendation: 'Integrate validateCloneParity for 100/100 parity scoring across visual, content, SEO, functional dimensions', closable: true, source: 'xtremeaibuilder' },
  { gap: 'No backend reconstruction', severity: 'high', category: 'Site Cloning', recommendation: 'Integrate reconstructBackend to analyze frontend and infer API endpoints, data models, business logic', closable: true, source: 'xtremeaibuilder' },
  { gap: 'No 5-dimension system audit', severity: 'critical', category: 'System Analysis', recommendation: 'Integrate Vision Cortex deepSystemAudit for performance, SEO, security, accessibility, content scoring with perfection prompts', closable: true, source: 'visioncortex' },
  { gap: 'No DNA-based scoring with critical failure detection', severity: 'high', category: 'System Analysis', recommendation: 'Integrate dnaScoreSystem — aggregate never hides a critical gap', closable: true, source: 'visioncortex' },
  { gap: 'No AI council / multi-agent debate', severity: 'medium', category: 'AI Council', recommendation: 'Integrate council session for multi-perspective analysis and consensus', closable: true, source: 'visioncortex' },
  { gap: 'No shadow mode for stealth recon', severity: 'high', category: 'Shadow Mode', recommendation: 'Integrate shadow browse/clone/forcefield for reconnaissance without detection', closable: true, source: 'visioncortex' },
  { gap: 'No factory system for autonomous project generation', severity: 'medium', category: 'Factory System', recommendation: 'Integrate factory seed/brand/content/website generators', closable: true, source: 'visioncortex' },
  { gap: 'No opportunity intelligence', severity: 'medium', category: 'Opportunity Intelligence', recommendation: 'Integrate opportunity sweep/research/follow-up for autonomous opportunity discovery', closable: true, source: 'visioncortex' },
  { gap: 'No enhancement engine with auto-recommend', severity: 'high', category: 'Enhancement Engine', recommendation: 'Integrate autoRecommend/autoEnhanceAll for autonomous system improvement', closable: true, source: 'visioncortex' },
  { gap: 'No multi-agent council', severity: 'medium', category: 'Agents', recommendation: 'Integrate Vision, Shadow, Strategy, Validator, Quant, Sage agents for multi-perspective intelligence', closable: true, source: 'visioncortex' },
  { gap: 'No business formation / legal docs', severity: 'medium', category: 'Business Operations', recommendation: 'Integrate business formation, legal document generator, e-signature from Xtreme AI Builder', closable: true, source: 'xtremeaibuilder' },
  { gap: 'No lead generation pipeline', severity: 'medium', category: 'Lead Generation', recommendation: 'Integrate lead capture, scoring, outreach, auto-respond from Xtreme AI Builder', closable: true, source: 'xtremeaibuilder' },
  { gap: 'No competitor analysis', severity: 'medium', category: 'Discovery', recommendation: 'Integrate competitor analysis, top performer discovery, industry knowledge scraping', closable: true, source: 'xtremeaibuilder' },
  { gap: 'No GHL CRM integration', severity: 'low', category: 'Business Automation', recommendation: 'Integrate GoHighLevel CRM from Fault-Line 3', closable: true, source: 'faultline' },
  { gap: 'No client portal', severity: 'low', category: 'Business Automation', recommendation: 'Integrate client portal with project visibility from Fault-Line 3', closable: true, source: 'faultline' },
  { gap: 'No master quality score', severity: 'medium', category: 'QA', recommendation: 'Integrate master quality scoring across all dimensions from Fault-Line 3', closable: true, source: 'faultline' },
  { gap: 'No recursive self-audit', severity: 'medium', category: 'QA', recommendation: 'Integrate recursive audit script from Fault-Line 3', closable: true, source: 'faultline' },
  { gap: 'No distributed browser grid', severity: 'high', category: 'Infrastructure', recommendation: 'Deploy globally distributed browser nodes with edge computing', closable: false, source: 'all' },
  { gap: 'No Kubernetes orchestration', severity: 'medium', category: 'Infrastructure', recommendation: 'Migrate to K8s-managed browser pods with HPA', closable: false, source: 'all' },
  { gap: 'No GPU acceleration', severity: 'medium', category: 'Infrastructure', recommendation: 'Add GPU-accelerated rendering for WebGL/WebGPU sites', closable: false, source: 'all' },
  { gap: 'No mobile device farm', severity: 'medium', category: 'Infrastructure', recommendation: 'Add real mobile devices for mobile browser testing', closable: false, source: 'all' },
  { gap: 'No GraphQL API', severity: 'low', category: 'Developer Experience', recommendation: 'Add GraphQL API for flexible client queries', closable: true, source: 'all' },
  { gap: 'No JS/TS SDK', severity: 'low', category: 'Developer Experience', recommendation: 'Create JavaScript/TypeScript SDK alongside Python SDK', closable: true, source: 'all' },
  { gap: 'No ML-based bot detection bypass', severity: 'high', category: 'Anti-Detection', recommendation: 'Train ML models to evade advanced bot detection systems', closable: false, source: 'all' },
  { gap: 'No reCAPTCHA v3/Enterprise solver', severity: 'high', category: 'CAPTCHA', recommendation: 'Add score-based reCAPTCHA v3 and Enterprise solvers', closable: true, source: 'all' },
  { gap: 'No Funcaptcha/Geetest solver', severity: 'medium', category: 'CAPTCHA', recommendation: 'Add Arkose Labs Funcaptcha and Geetest solvers', closable: true, source: 'all' },
  { gap: 'No full SOC 2 / HIPAA compliance', severity: 'high', category: 'Compliance', recommendation: 'Implement full compliance frameworks with audit support', closable: true, source: 'all' },
  { gap: 'No chaos engineering', severity: 'low', category: 'Reliability', recommendation: 'Add chaos testing for resilience validation', closable: true, source: 'all' },
  { gap: 'No distributed tracing', severity: 'medium', category: 'Observability', recommendation: 'Add OpenTelemetry distributed tracing', closable: true, source: 'all' },
  { gap: 'No visual element recognition', severity: 'medium', category: 'AI', recommendation: 'AI-powered visual element identification without CSS selectors', closable: true, source: 'all' },
  { gap: 'No predictive failure detection', severity: 'medium', category: 'AI', recommendation: 'ML model to predict job failures before they happen', closable: true, source: 'all' },
  { gap: 'No knowledge graph construction', severity: 'low', category: 'AI', recommendation: 'Build knowledge graphs from extracted data', closable: true, source: 'all' },
  { gap: 'No WebSocket message capture', severity: 'medium', category: 'Data Extraction', recommendation: 'Capture WebSocket messages for real-time data extraction', closable: true, source: 'all' },
  { gap: 'No video/audio transcription', severity: 'low', category: 'Data Extraction', recommendation: 'Transcribe video and audio content from pages', closable: true, source: 'all' },
];

// === VISION CORTEX STRATEGIC ENHANCEMENTS ===
export const VISION_CORTEX_STRATEGIES = [
  { name: '5-Dimension Perfection Cycle', description: 'Autonomous cycle that audits performance, SEO, security, accessibility, and content — then generates zero-ambiguity perfection prompts to bring each dimension from current score to 100%', source: 'visioncortex', priority: 'critical' },
  { name: 'DNA Multi-Score Model', description: 'Multi-score system where the aggregate NEVER hides a critical failure — if any capability has a critical gap, the score is capped regardless of the average', source: 'visioncortex', priority: 'critical' },
  { name: 'Council of Agents', description: 'Multi-agent council (Vision, Shadow, Strategy, Validator, Quant, Sage, Philosopher, Capital, Treasurer) that debates, predicts, and compounds intelligence for strategic decisions', source: 'visioncortex', priority: 'high' },
  { name: 'Shadow Reconnaissance', description: 'Stealth browsing mode that gathers intelligence, hunts for revenue opportunities, checks sentiment, and logs performance — all without triggering bot detection', source: 'visioncortex', priority: 'high' },
  { name: 'Factory Production Line', description: 'Autonomous factory system that generates complete projects: seed → brand → content → domain → website → growth OS → social AI, all from a single specification', source: 'visioncortex', priority: 'high' },
  { name: 'Opportunity Sweep Engine', description: 'Autonomous opportunity scanning that discovers, researches, follows up on, and responds to business opportunities in real-time', source: 'visioncortex', priority: 'medium' },
  { name: 'Enhancement Auto-Approver', description: 'Autonomous enhancement engine that recommends, approves, implements, and validates system improvements with zero human intervention', source: 'visioncortex', priority: 'high' },
  { name: 'Life Simulation & Drift Detection', description: 'Simulate outcomes, strategies, and user journeys — then lock plans and detect when reality drifts from the simulation', source: 'visioncortex', priority: 'medium' },
  { name: 'Deep System Audit with Live Context', description: 'Browse the live site via Cloud Browser, run a full 5-dimension audit WITH live web context, classify system type, detect tech stack, research benchmark, and generate perfection prompts', source: 'visioncortex', priority: 'critical' },
  { name: 'DNA Traceability Chain', description: 'Full traceability from requirement → capability → gap → fix → verification, ensuring every system change is tracked and auditable', source: 'visioncortex', priority: 'high' },
  { name: 'Gap-to-Perfection Pipeline', description: 'For each gap found, generate a complete, self-contained, copy-paste-ready prompt that an autonomous builder could execute to close the gap and reach 100%', source: 'visioncortex', priority: 'critical' },
  { name: 'Compound Intelligence', description: 'Council sessions where multiple agents contribute perspectives, debate outcomes, and compound their intelligence into a single strategic blueprint', source: 'visioncortex', priority: 'medium' },
];

// === VISION CORTEX SKILL PLAYBOOK ===
export const VISION_CORTEX_PLAYBOOK = [
  { skill: 'Visual Clone Parity', playbook: '1) Browse original site → 2) Screenshot every page → 3) Extract Design DNA (colors, fonts, spacing) → 4) Generate clone → 5) Screenshot clone → 6) Run Vision Cortex Compare → 7) Auto-adjust until parity ≥ 95% → 8) Validate across visual, content, SEO, functional → 9) Deploy', source: 'xtremeaibuilder' },
  { skill: 'Deep System Audit', playbook: '1) Browse live site via Cloud Browser → 2) Capture page content → 3) Run 5-dimension audit with live web context → 4) Classify system type → 5) Detect tech stack → 6) Research #1 benchmark → 7) Generate perfection prompt per dimension → 8) Synthesize overall summary → 9) Determine launch readiness', source: 'visioncortex' },
  { skill: 'DNA Gap Analysis', playbook: '1) List all system capabilities → 2) Score each 0-100 → 3) Identify critical gaps → 4) Cap aggregate if any critical → 5) Generate gap-to-perfection prompts → 6) Prioritize by impact → 7) Dispatch to builder → 8) Track to 100%', source: 'visioncortex' },
  { skill: 'Shadow Reconnaissance', playbook: '1) Enter shadow mode → 2) Browse target stealthily → 3) Capture site defenses (captcha, bot detection, rate limits) → 4) Hunt for revenue opportunities → 5) Check sentiment → 6) Log performance → 7) Save to Drive → 8) Schedule milestones → 9) Exit shadow → 10) Generate strategy', source: 'visioncortex' },
  { skill: 'Council Deliberation', playbook: '1) Convene council (Vision, Shadow, Strategy, Validator, Quant, Sage) → 2) Present topic → 3) Each agent provides perspective → 4) Structured debate → 5) Predict outcomes → 6) Compound intelligence → 7) Generate blueprint → 8) Vote → 9) Execute decision', source: 'visioncortex' },
  { skill: 'Factory Production', playbook: '1) Input specification → 2) Generate seed → 3) Research industry → 4) Generate brand pack → 5) Generate content → 6) Check domain → 7) Generate website → 8) Generate growth OS → 9) Generate social AI → 10) Provision Supabase → 11) Provision Vercel → 12) Launch', source: 'visioncortex' },
  { skill: 'Enhancement Cycle', playbook: '1) Scan system → 2) Detect gaps → 3) Auto-recommend enhancements → 4) Auto-approve low-risk → 5) Queue high-risk for human → 6) Implement approved → 7) Validate → 8) Score → 9) Repeat until 100%', source: 'visioncortex' },
  { skill: 'Opportunity Sweep', playbook: '1) Sweep intelligence sources → 2) Ingest intel → 3) Detect opportunities → 4) Research each → 5) Score viability → 6) Follow up → 7) Respond automatically → 8) Track outcomes', source: 'visioncortex' },
  { skill: 'Clone Deployment', playbook: '1) Clone full site → 2) Extract Design DNA → 3) Generate website from DNA → 4) Validate parity → 5) Provision Vercel deployment → 6) Assign domain → 7) Configure DNS → 8) Validate live → 9) Track in Clone Library', source: 'xtremeaibuilder' },
  { skill: 'Self-Heal Pipeline', playbook: '1) Detect deployment issue → 2) Analyze error → 3) Generate fix → 4) Apply fix → 5) Validate → 6) If fail, retry with different approach → 7) Log activity → 8) Notify on success/failure', source: 'xtremeaibuilder' },
];

// Combine all capabilities
export const ALL_CAPABILITIES = [
  ...CURRENT_CAPABILITIES,
  ...XTREMEAI_CAPABILITIES,
  ...FAULTLINE_CAPABILITIES,
  ...VISIONCORTEX_CAPABILITIES,
  ...ALL_POSSIBLE_CAPABILITIES,
];

export const SCORE_DIMENSIONS = [
  { key: 'infrastructure', label: 'Infrastructure', weight: 15, description: 'Browser engine, scaling, deployment, session management' },
  { key: 'anti_detection', label: 'Anti-Detection', weight: 12, description: 'Fingerprinting, bot bypass, human simulation, stealth' },
  { key: 'captcha', label: 'CAPTCHA Solving', weight: 10, description: 'Self-solving, provider fallback, vision-based solving' },
  { key: 'extraction', label: 'Data Extraction', weight: 15, description: 'Text, HTML, media, structured data, API interception' },
  { key: 'ai', label: 'AI & Intelligence', weight: 15, description: 'Self-healing, NLP, visual recognition, auto-retry' },
  { key: 'security', label: 'Security & Compliance', weight: 12, description: 'Encryption, RLS, SSRF, audit, compliance frameworks' },
  { key: 'scale', label: 'Performance & Scale', weight: 8, description: 'Concurrency, autoscaling, tracing, circuit breakers' },
  { key: 'dx', label: 'Developer Experience', weight: 8, description: 'SDKs, APIs, CLI, documentation, MCP' },
  { key: 'governance', label: 'Governance', weight: 5, description: 'RLS, quotas, budgets, sandboxes, settings' },
];